### ISSUE TITLE
tenplay not working

### ISSUE THREAD

**Issue by AuXBoX** [xbmc-catchuptv-au/repo#13]
I can't get any videos to play. This is only recently. Tenplay has always been very slow to list tvshows aswell

**Comment by AuXBoX** [comment]
the error is 
WARNING: CPythonInvoker(17, /home/xbmc/.kodi/addons/plugin.video.catchuptv.au.ten/default.py): the python script "/home/xbmc/.kodi/addons/plugin.video.catchuptv.au.ten/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

**Comment by AuXBoX** [comment]
Fixed...
The error was actually 
ERROR: Unable to load librtmp.so.1, reason: librtmp.so.1: cannot open shared object file: No such file or directory
so installed librtmp-dev

**Comment by missgeeves** [comment]
With the listing of tvshows being very slow, I found it quite unworkable - it was taking upwards of 10-15 mins to load the list on my raspberry pi. It seemed to be related to the fanart so I went searching and have replaced one line in one file. Disclaimer: I know zip about python! I thought by this edit I would get the listing without the fanart thumbnails but in fact I still get them. It's gone down to about a 30 second listing time now though which is acceptable if not perfect.

So, in ~/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/networktenaddon/showlist.py I replaced line 120:

fanart_url = api.get_fanart(show)

with 

fanart_url = None

I don't know why it works but it does.

**Comment by adammw** [comment]
@AuXBoX The Ten plugin uses RTMP streams to play the actual video, so you'll need to have XBMC compiled with rtmp support. 

@missgeeves Yep, the Raspberry Pi seems to be very slow when doing all the image processing and searching for fanart (due to XBMC API we can't do it in the background, so the process of searching through the webpages and fetching the fanart actually slows down the loading of the list). I've heard this from a number of people, I haven't had the chance to work out the best solution yet.

I'm going to close this issue and transfer the slowness on Raspberry Pi issue to the plugin issue tracker: https://github.com/xbmc-catchuptv-au/plugin.video.catchuptv.au.ten/issues/421.
